//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cimenOtoV11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesafeliSatisSozlesmeleri
    {
        public int SozlesmeID { get; set; }
        public Nullable<System.Guid> MusteriID { get; set; }
        public Nullable<int> SiparisID { get; set; }
        public string SozlesmeMetni { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
    
        public virtual tbl_Siparisler tbl_Siparisler { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
