//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cimenOtoV11.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_CimenOtoEntities : DbContext
    {
        public db_CimenOtoEntities()
            : base("name=db_CimenOtoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MesafeliSatisSozlesmeleri> MesafeliSatisSozlesmeleri { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Adres> tbl_Adres { get; set; }
        public virtual DbSet<tbl_AracMarka> tbl_AracMarka { get; set; }
        public virtual DbSet<tbl_AracModel> tbl_AracModel { get; set; }
        public virtual DbSet<tbl_AracParca> tbl_AracParca { get; set; }
        public virtual DbSet<tbl_Sepet> tbl_Sepet { get; set; }
        public virtual DbSet<tbl_SİparisDetay> tbl_SİparisDetay { get; set; }
        public virtual DbSet<tbl_SiparisDurum> tbl_SiparisDurum { get; set; }
        public virtual DbSet<tbl_Siparisler> tbl_Siparisler { get; set; }
        public virtual DbSet<tbl_TeslimatIade> tbl_TeslimatIade { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<tbl_Yorum> tbl_Yorum { get; set; }
    }
}
