//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cimenOtoV11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_User()
        {
            this.MesafeliSatisSozlesmeleri = new HashSet<MesafeliSatisSozlesmeleri>();
            this.tbl_Adres = new HashSet<tbl_Adres>();
            this.tbl_Sepet = new HashSet<tbl_Sepet>();
            this.tbl_Siparisler = new HashSet<tbl_Siparisler>();
            this.tbl_Siparisler1 = new HashSet<tbl_Siparisler>();
            this.tbl_Yorum = new HashSet<tbl_Yorum>();
        }
    
        public System.Guid kulID { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string eMail { get; set; }
        public string telNo { get; set; }
        public Nullable<byte> adminMi { get; set; }
        public Nullable<int> adres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MesafeliSatisSozlesmeleri> MesafeliSatisSozlesmeleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Adres> tbl_Adres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Sepet> tbl_Sepet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Siparisler> tbl_Siparisler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Siparisler> tbl_Siparisler1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Yorum> tbl_Yorum { get; set; }
    }
}
