//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cimenOtoV11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TeslimatIade
    {
        public int id { get; set; }
        public string metin { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string adres { get; set; }
    }
}
