//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cimenOtoV11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Yorum
    {
        public int yorumID { get; set; }
        public Nullable<System.Guid> kulID { get; set; }
        public Nullable<int> parcaID { get; set; }
        public Nullable<byte> yildiz { get; set; }
        public string yorum { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual tbl_AracParca tbl_AracParca { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
