//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cimenOtoV11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AracModel
    {
        public short modelID { get; set; }
        public Nullable<int> markaID { get; set; }
        public string modelAdi { get; set; }
        public string modelYili { get; set; }
    
        public virtual tbl_AracMarka tbl_AracMarka { get; set; }
    }
}
