//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cimenOtoV11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Adres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Adres()
        {
            this.tbl_SİparisDetay = new HashSet<tbl_SİparisDetay>();
            this.tbl_Siparisler = new HashSet<tbl_Siparisler>();
        }
    
        public int adresID { get; set; }
        public Nullable<System.Guid> userID { get; set; }
        public string adresSatir1 { get; set; }
        public string adresSatir2 { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string postaKodu { get; set; }
        public string adresTuru { get; set; }
        public Nullable<bool> varsayilanMi { get; set; }
        public Nullable<System.DateTime> olusturmaTarih { get; set; }
    
        public virtual tbl_User tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SİparisDetay> tbl_SİparisDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Siparisler> tbl_Siparisler { get; set; }
    }
}
