//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cimenOtoV11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AracParca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_AracParca()
        {
            this.tbl_Sepet = new HashSet<tbl_Sepet>();
            this.tbl_SİparisDetay = new HashSet<tbl_SİparisDetay>();
            this.tbl_Yorum = new HashSet<tbl_Yorum>();
        }
    
        public int parcaID { get; set; }
        public Nullable<int> markaID { get; set; }
        public string modelID { get; set; }
        public string Uretici { get; set; }
        public string ureticiKod { get; set; }
        public string orginalKod { get; set; }
        public string pAd { get; set; }
        public string aciklama { get; set; }
        public string icerik { get; set; }
        public string motorTip { get; set; }
        public string yil { get; set; }
        public Nullable<decimal> isk { get; set; }
        public Nullable<decimal> kdv { get; set; }
        public Nullable<decimal> listeFiyat { get; set; }
        public Nullable<decimal> kdvMaliyet { get; set; }
        public Nullable<byte> stokMiktari { get; set; }
        public string parcaImage { get; set; }
    
        public virtual tbl_AracMarka tbl_AracMarka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Sepet> tbl_Sepet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SİparisDetay> tbl_SİparisDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Yorum> tbl_Yorum { get; set; }
    }
}
